version: '3.9'

services:
  valheim-server-discord-bot:
    container_name: valheim-server-discord-bot
    image: ghcr.io/floryn08/valheim-server-discord-bot:master
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      GUILD_ID: ${GUILD_ID}
      PORTAINER_URL: ${PORTAINER_URL}
      PORTAINER_API_KEY: ${PORTAINER_API_KEY}
      CONTAINER_NAME: ${CONTAINER_NAME}
      SERVER_NAME: ${SERVER_NAME}
      JOIN_CODE_LOOP_COUNT: ${JOIN_CODE_LOOP_COUNT}
      JOIN_CODE_LOOP_TIMEOUT_MILLIS: ${JOIN_CODE_LOOP_TIMEOUT_MILLIS}
    volumes:
      - /home/flow/appdata/game-servers/valheim-server-discord-bot:/app/config.js:ro
    restart: unless-stopped
