apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-discord-bot
  namespace: {{ .Values.namespace }}
roleRef:
  name: {{ .Release.Name }}-discord-bot
  kind: Role
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-discord-bot
    namespace: {{ .Values.namespace }}
