name: Create Tag

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Initial checkout
        uses: actions/checkout@v4.1.4
        with:
          fetch-depth: "0"
          token: ${{secrets.ACCESS_TOKEN}}

      - name: Setup Git
        run: |
          git config user.email ${{secrets.EMAIL}}
          git config user.name ${{secrets.NAME}}

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          cache: "npm"
          node-version: "20"

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: "5.x"

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v1.1.1

      - name: Display SemVer
        run: |
          echo "SemVer: $semVer" && echo "$major.$minor.$patch"

      - name: Bump package.json
        run: |
          npm version ${{env.semVer}} --allow-same-version --git-tag-version false
          npm ci

      - name: Bump helm chart
        run: |
          sed -i "s/^version:.*/version: ${{env.semVer}}/" deployment/helm/Chart.yaml
          sed -i "s/:[0-9]\+\.[0-9]\+\.[0-9]\+/:${{env.semVer}}/" deployment/helm/values.yaml

      - name: Push version updates and create tags
        run: |
          git add .
          git commit -m "ci: version bump ${{env.semVer}}"
          git tag ${{env.semVer}}
          git push
          git push origin tag ${{env.semVer}}
